import type { Article, ArticleImage } from "./types";

/* ==========================================================================
   HyperNews content
   Real, hand-written articles across three focused verticals:
   · Inteligencia Artificial (y herramientas útiles)
   · Psicología cotidiana (relaciones y comportamiento)
   · Historia de empresas, negocios y tecnología
   Every article is navigable and complete — no filler, no empty sections.
   ========================================================================== */

/** Build an editorial photo from a verified Unsplash id. */
function img(id: string, alt: string, credit = "Unsplash"): ArticleImage {
  return {
    url: `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1600&q=70`,
    alt,
    credit,
  };
}

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

// ── INTELIGENCIA ARTIFICIAL ────────────────────────────────────────────────
const ia: Article[] = [
  {
    slug: "herramientas-ia-productividad-diaria",
    title: "7 herramientas de IA que de verdad ahorran tiempo (y cómo usarlas bien)",
    excerpt:
      "Menos hype y más práctica: una guía honesta de las herramientas de inteligencia artificial que merecen un hueco en tu rutina.",
    image: img("1620712943543-bcc4688e7485", "Interfaz abstracta de inteligencia artificial"),
    coverSeed: "ia-tools",
    category: "inteligencia-artificial",
    tags: ["herramientas", "productividad", "guía"],
    author: "elena-marquez",
    publishedAt: daysAgo(3),
    updatedAt: daysAgo(1),
    featured: true,
    trending: true,
    views: 41200,
    comments: 68,
    blocks: [
      { type: "paragraph", text: "La inteligencia artificial ha pasado de ser una curiosidad a formar parte del trabajo cotidiano de millones de personas. Pero entre tanto anuncio grandilocuente cuesta distinguir lo que sirve de lo que solo hace ruido. Esta es una selección honesta: herramientas que usamos de verdad y el modo correcto de sacarles partido." },
      { type: "heading", level: 2, text: "1. Asistentes conversacionales para pensar en voz alta", id: "asistentes" },
      { type: "paragraph", text: "Un buen asistente de IA no es un oráculo, sino un compañero de pensamiento. Funciona mejor cuando le das contexto y le pides que razone paso a paso, no cuando esperas la respuesta perfecta al primer intento." },
      { type: "callout", tone: "tip", title: "El truco", text: "Trata a la IA como a un becario brillante pero sin memoria: dale el objetivo, los datos y el formato de salida. La calidad de la respuesta depende de la calidad de la pregunta." },
      { type: "heading", level: 2, text: "2. Transcripción y resúmenes de reuniones", id: "transcripcion" },
      { type: "paragraph", text: "Las herramientas que graban, transcriben y resumen reuniones se han vuelto sorprendentemente fiables. Recuperas horas que antes se iban en tomar notas y puedes volver a cualquier decisión con una búsqueda." },
      { type: "heading", level: 2, text: "3. Redacción y edición asistida", id: "redaccion" },
      { type: "paragraph", text: "Para superar el folio en blanco, pedir un primer borrador es oro. El error habitual es publicar tal cual: la IA acierta con la estructura, pero el criterio, los matices y la voz siguen siendo tuyos." },
      { type: "list", ordered: false, items: [
        "**Genera opciones**, no una única versión: pide tres enfoques y elige.",
        "**Revisa siempre los datos**: la IA inventa cifras con total seguridad.",
        "**Guarda tus mejores prompts**: son tu verdadera ventaja competitiva.",
      ] },
      { type: "quote", text: "La IA no sustituye tu criterio; multiplica tu capacidad de ejecutar lo que ya sabes decidir.", cite: "Elena Márquez" },
      { type: "heading", level: 2, text: "Cómo elegir sin perderte", id: "como-elegir" },
      { type: "paragraph", text: "No necesitas veinte suscripciones. Elige una herramienta por tarea recurrente que te robe tiempo, domínala durante dos semanas y solo entonces añade la siguiente. La constancia vence a la novedad." },
      { type: "faq", items: [
        { q: "¿Son seguros mis datos con estas herramientas?", a: "Depende del proveedor. Revisa si usan tus datos para entrenar sus modelos y evita introducir información confidencial en servicios gratuitos." },
        { q: "¿Merece la pena pagar la versión de pago?", a: "Si usas una herramienta a diario para trabajar, casi siempre sí: el tiempo ahorrado supera con creces el coste mensual." },
        { q: "¿La IA va a quitarme el trabajo?", a: "Más bien cambia las tareas. Quien aprende a delegar lo repetitivo en la IA y se concentra en el criterio gana ventaja." },
      ] },
    ],
  },
  {
    slug: "como-escribir-buenos-prompts",
    title: "El arte de pedir bien: cómo escribir prompts que funcionan",
    excerpt: "La diferencia entre una respuesta mediocre y una brillante casi nunca está en el modelo, sino en cómo formulas la pregunta.",
    image: img("1677442136019-21780ecad995", "Persona escribiendo instrucciones en una interfaz de IA"),
    coverSeed: "prompts",
    category: "inteligencia-artificial",
    tags: ["prompts", "guía", "productividad"],
    author: "dario-fuentes",
    publishedAt: daysAgo(9),
    trending: true,
    views: 28700,
    comments: 41,
    blocks: [
      { type: "paragraph", text: "Escribir un buen prompt se parece a delegar una tarea a alguien competente: cuanto más claro seas con el contexto, el objetivo y el resultado esperado, mejor será lo que recibes. La buena noticia es que es una habilidad que se aprende rápido." },
      { type: "heading", level: 2, text: "Da contexto, no solo una orden", id: "contexto" },
      { type: "paragraph", text: "«Escribe un email» produce algo genérico. «Escribe un email breve y cordial a un cliente que lleva dos semanas sin responder, recordándole la propuesta sin sonar insistente» produce algo utilizable. El contexto es la mitad del trabajo." },
      { type: "heading", level: 2, text: "Pide un rol y un formato", id: "rol-formato" },
      { type: "paragraph", text: "Indicar «actúa como editor exigente» o «responde en forma de lista con pros y contras» orienta al modelo hacia el tipo de respuesta que necesitas y reduce las divagaciones." },
      { type: "callout", tone: "info", title: "Plantilla útil", text: "Contexto + Objetivo + Restricciones + Formato de salida. Si tu prompt incluye esas cuatro piezas, ya estás por delante del 90% de la gente." },
      { type: "heading", level: 2, text: "Itera en lugar de rendirte", id: "itera" },
      { type: "paragraph", text: "La primera respuesta rara vez es la definitiva. Corrige con frases cortas: «más concreto», «con ejemplos», «tono más informal». Conversar con la herramienta es parte del método, no un fallo." },
      { type: "list", ordered: true, items: [
        "Empieza amplio y ve acotando.",
        "Pide que te haga preguntas si le falta información.",
        "Guarda los prompts que te funcionen: son reutilizables.",
      ] },
    ],
  },
  {
    slug: "ia-generativa-imagenes-para-no-disenadores",
    title: "IA generativa de imágenes para quien no sabe diseñar",
    excerpt: "Crear ilustraciones y gráficos decentes ya no exige años de práctica. Te contamos cómo empezar y dónde están los límites.",
    image: img("1526374965328-7f61d4dc18c5", "Código y visuales generados digitalmente"),
    coverSeed: "gen-img",
    category: "inteligencia-artificial",
    tags: ["imágenes", "diseño", "herramientas"],
    author: "elena-marquez",
    publishedAt: daysAgo(16),
    views: 19400,
    comments: 22,
    blocks: [
      { type: "paragraph", text: "Durante años, ilustrar un artículo o una presentación implicaba pagar a un diseñador o conformarse con bancos de imágenes repetidos. La IA generativa ha cambiado esa ecuación para todo el mundo." },
      { type: "heading", level: 2, text: "Describe lo que imaginas", id: "describe" },
      { type: "paragraph", text: "Estas herramientas convierten texto en imagen. Cuanto más específico seas —estilo, luz, encuadre, colores— más control tendrás. «Ilustración plana, colores cálidos, fondo claro» da resultados muy distintos a una descripción vaga." },
      { type: "heading", level: 2, text: "Dónde brilla y dónde falla", id: "limites" },
      { type: "paragraph", text: "Brilla en conceptos, fondos y estilos ilustrativos. Falla todavía con el texto dentro de la imagen, las manos y la coherencia entre varias imágenes de una misma serie. Conocer esos límites te ahorra frustración." },
      { type: "callout", tone: "warn", title: "Ojo con los derechos", text: "Revisa la licencia de la herramienta antes de usar imágenes con fines comerciales. No todo lo que puedes generar puedes venderlo." },
      { type: "paragraph", text: "Nuestro consejo: úsala para bocetar rápido y comunicar ideas, y reserva al profesional para las piezas donde la marca se lo juega todo. La IA amplía el suelo, no sustituye el techo." },
    ],
  },
  {
    slug: "chatbots-atencion-cliente-pequena-empresa",
    title: "Chatbots de IA para pequeñas empresas: cuándo sí y cuándo no",
    excerpt: "Automatizar la atención al cliente puede liberar horas o arruinar tu reputación. La clave está en dónde pones la frontera.",
    image: img("1531746790731-6c087fecd65a", "Robot conversacional representando atención automatizada"),
    coverSeed: "chatbot",
    category: "inteligencia-artificial",
    tags: ["negocios", "automatización", "herramientas"],
    author: "noa-ibrahim",
    publishedAt: daysAgo(24),
    views: 15200,
    comments: 30,
    blocks: [
      { type: "paragraph", text: "Un chatbot bien planteado responde al instante las preguntas repetitivas y deja a tu equipo lo que de verdad requiere una persona. Uno mal planteado convierte una duda simple en un laberinto que enfada al cliente." },
      { type: "heading", level: 2, text: "Automatiza lo predecible", id: "predecible" },
      { type: "paragraph", text: "Horarios, estado de un pedido, preguntas frecuentes: ahí la IA es imbatible. Responde 24/7, no se cansa y aprende de las conversaciones. Empieza por lo que ya preguntan mil veces." },
      { type: "heading", level: 2, text: "Deja lo humano a los humanos", id: "humano" },
      { type: "paragraph", text: "Una reclamación delicada, una venta importante o un cliente enfadado necesitan empatía real. El mejor diseño ofrece siempre una salida clara: «hablar con una persona». Esconder ese botón es el error más caro." },
      { type: "list", ordered: false, items: [
        "Sé transparente: el cliente debe saber que habla con un bot.",
        "Mide la tasa de resolución, no solo el volumen de mensajes.",
        "Revisa las conversaciones fallidas cada semana y mejora.",
      ] },
      { type: "quote", text: "La automatización que oculta a las personas no ahorra costes: los traslada al cliente en forma de frustración.", cite: "Noa Ibrahim" },
    ],
  },
  {
    slug: "que-es-un-modelo-de-lenguaje",
    title: "Qué es realmente un modelo de lenguaje (explicado sin tecnicismos)",
    excerpt: "Entender cómo funciona por dentro la IA que usas a diario te convierte en un usuario mucho más eficaz y crítico.",
    image: img("1451187580459-43490279c0fa", "Red de conexiones representando un modelo de lenguaje"),
    coverSeed: "llm",
    category: "inteligencia-artificial",
    tags: ["conceptos", "guía"],
    author: "dario-fuentes",
    publishedAt: daysAgo(33),
    views: 22100,
    comments: 27,
    blocks: [
      { type: "paragraph", text: "Un modelo de lenguaje es, en esencia, un sistema que ha leído cantidades ingentes de texto y ha aprendido a predecir qué palabra viene después. Suena simple, y en el fondo lo es, pero de esa simpleza emergen capacidades sorprendentes." },
      { type: "heading", level: 2, text: "Predicción, no comprensión", id: "prediccion" },
      { type: "paragraph", text: "El modelo no «entiende» como tú. Calcula probabilidades a partir de patrones. Por eso puede sonar convincente y equivocarse a la vez: acierta la forma del lenguaje aunque falle el contenido." },
      { type: "callout", tone: "info", title: "Por qué alucina", text: "Cuando no sabe algo, el modelo no calla: genera la continuación más plausible. A eso lo llamamos «alucinación», y es la razón por la que siempre debes verificar los datos importantes." },
      { type: "heading", level: 2, text: "Qué implica para ti", id: "implicaciones" },
      { type: "paragraph", text: "Saber esto cambia cómo lo usas: pides fuentes, contrastas cifras y aprovechas su fuerza —redactar, resumir, reformular— sin delegar en él las decisiones que exigen verdad verificada." },
    ],
  },
  {
    slug: "automatizar-tareas-repetitivas-con-ia",
    title: "Cómo automatizar tus tareas repetitivas con IA en una tarde",
    excerpt: "No necesitas saber programar para quitarte de encima el trabajo aburrido. Un método sencillo para empezar hoy mismo.",
    image: img("1517486808906-6ca8b3f04846", "Escritorio de trabajo con portátil y notas"),
    coverSeed: "automation",
    category: "inteligencia-artificial",
    tags: ["automatización", "productividad", "herramientas"],
    author: "elena-marquez",
    publishedAt: daysAgo(45),
    views: 17800,
    comments: 19,
    blocks: [
      { type: "paragraph", text: "Todos tenemos tareas que se repiten cada semana y que, sumadas, se comen horas: clasificar correos, preparar informes, dar formato a datos. La IA, combinada con herramientas de automatización sencillas, puede encargarse de buena parte." },
      { type: "heading", level: 2, text: "Haz una lista de lo que odias hacer", id: "lista" },
      { type: "paragraph", text: "El primer paso no es técnico, es de observación. Durante una semana anota cada tarea repetitiva. Verás patrones claros: eso es exactamente lo que conviene automatizar primero." },
      { type: "heading", level: 2, text: "Empieza pequeño y visible", id: "pequeno" },
      { type: "paragraph", text: "Automatiza una sola cosa de principio a fin antes de soñar con un sistema complejo. Un pequeño éxito que funciona todos los días motiva más que un gran proyecto que nunca terminas." },
      { type: "list", ordered: true, items: [
        "Identifica una tarea con reglas claras.",
        "Descríbela paso a paso, como se lo explicarías a alguien.",
        "Prueba, mide el tiempo ahorrado y ajusta.",
      ] },
      { type: "paragraph", text: "La meta no es automatizarlo todo, sino recuperar tu atención para lo que solo tú puedes hacer." },
    ],
  },
];

// ── PSICOLOGÍA ─────────────────────────────────────────────────────────────
const psicologia: Article[] = [
  {
    slug: "por-que-procrastinamos",
    title: "Por qué procrastinamos (y no es porque seas vago)",
    excerpt: "La procrastinación no es un problema de pereza, sino de emociones. Entenderlo es el primer paso para vencerla.",
    image: img("1499750310107-5fef28a66643", "Persona escribiendo en un cuaderno junto a un café"),
    coverSeed: "procrastinacion",
    category: "psicologia",
    tags: ["hábitos", "comportamiento", "productividad"],
    author: "mara-costa",
    publishedAt: daysAgo(2),
    featured: true,
    trending: true,
    views: 38900,
    comments: 74,
    blocks: [
      { type: "paragraph", text: "Solemos culparnos por procrastinar como si fuera un defecto de carácter. Pero la ciencia del comportamiento cuenta otra historia: postergamos no porque seamos perezosos, sino porque intentamos evitar una emoción incómoda asociada a la tarea." },
      { type: "heading", level: 2, text: "Un problema emocional, no de gestión del tiempo", id: "emocional" },
      { type: "paragraph", text: "Cuando una tarea nos genera aburrimiento, ansiedad o miedo al fracaso, el cerebro busca alivio inmediato. Revisar el móvil o limpiar la cocina calma esa incomodidad a corto plazo, aunque la agrave a largo plazo." },
      { type: "callout", tone: "tip", title: "La clave", text: "No preguntes «¿cómo me organizo mejor?», sino «¿qué emoción estoy evitando?». Ahí está la verdadera palanca del cambio." },
      { type: "heading", level: 2, text: "Estrategias que sí funcionan", id: "estrategias" },
      { type: "list", ordered: false, items: [
        "**Reduce la fricción inicial:** comprométete solo con dos minutos. Empezar es casi todo.",
        "**Perdónate:** la culpa alimenta el ciclo. Los estudios muestran que quien se perdona procrastina menos la próxima vez.",
        "**Haz la emoción explícita:** nombrar «esto me da pereza porque temo hacerlo mal» le quita fuerza.",
      ] },
      { type: "quote", text: "No procrastinamos tareas; procrastinamos las emociones que esas tareas nos hacen sentir.", cite: "Mara Costa" },
      { type: "heading", level: 2, text: "El papel de la autocompasión", id: "autocompasion" },
      { type: "paragraph", text: "Tratarte con la amabilidad que tendrías con un amigo no es blandura: es eficacia. Reduce la ansiedad que dispara la evitación y te devuelve al trabajo antes. La dureza contigo mismo casi nunca es la solución." },
      { type: "faq", items: [
        { q: "¿La procrastinación es una enfermedad?", a: "No en sí misma, aunque puede relacionarse con la ansiedad o el TDAH. Para la mayoría es un patrón emocional aprendido que se puede modificar." },
        { q: "¿Sirve dividir las tareas en pasos pequeños?", a: "Mucho. Reduce la sensación de amenaza y facilita empezar, que es donde se gana la batalla." },
      ] },
    ],
  },
  {
    slug: "escucha-activa-relaciones",
    title: "Escuchar de verdad: el hábito que transforma tus relaciones",
    excerpt: "La mayoría no escuchamos para entender, sino para responder. Cambiar eso mejora cualquier vínculo, en casa y en el trabajo.",
    image: img("1544027993-37dbfe43562a", "Dos personas conversando con atención"),
    coverSeed: "escucha",
    category: "psicologia",
    tags: ["relaciones", "comunicación", "comportamiento"],
    author: "mara-costa",
    publishedAt: daysAgo(8),
    trending: true,
    views: 26400,
    comments: 45,
    blocks: [
      { type: "paragraph", text: "Creemos que sabemos escuchar, pero casi siempre estamos preparando nuestra respuesta mientras el otro habla. La escucha activa —atender de verdad, sin planear la réplica— es una de las habilidades más transformadoras y menos practicadas." },
      { type: "heading", level: 2, text: "Escuchar no es esperar tu turno", id: "turno" },
      { type: "paragraph", text: "La escucha genuina implica soltar por un momento tu propia agenda. No se trata de estar de acuerdo, sino de que la otra persona se sienta comprendida. Esa sensación, por sí sola, desactiva la mayoría de los conflictos." },
      { type: "heading", level: 2, text: "Tres gestos que lo cambian todo", id: "gestos" },
      { type: "list", ordered: true, items: [
        "**Refleja:** repite con tus palabras lo que has entendido antes de opinar.",
        "**Pregunta:** «¿qué es lo que más te preocupa de esto?» abre; «¿no crees que…?» cierra.",
        "**Tolera el silencio:** dar espacio invita al otro a profundizar.",
      ] },
      { type: "callout", tone: "info", title: "Prueba esto hoy", text: "En tu próxima conversación importante, propón un objetivo: que la otra persona termine diciendo «sí, exacto». Ahí sabrás que has escuchado bien." },
      { type: "paragraph", text: "Escuchar mejor no requiere talento, sino intención. Y sus efectos —en pareja, con los hijos, en el trabajo— se notan desde la primera conversación." },
    ],
  },
  {
    slug: "sesgos-cognitivos-decisiones",
    title: "Los sesgos que te engañan cada día al tomar decisiones",
    excerpt: "Tu mente toma atajos para ahorrar energía. Conocerlos no te vuelve inmune, pero sí bastante más sensato.",
    image: img("1493836512294-502baa1986e2", "Ilustración abstracta que representa la mente y el pensamiento"),
    coverSeed: "sesgos",
    category: "psicologia",
    tags: ["comportamiento", "decisiones", "mente"],
    author: "dario-fuentes",
    publishedAt: daysAgo(14),
    views: 20800,
    comments: 33,
    blocks: [
      { type: "paragraph", text: "El cerebro humano es una máquina de ahorrar energía. Para no analizar cada decisión desde cero, usa atajos mentales llamados sesgos cognitivos. Suelen funcionar, pero también nos hacen equivocarnos de forma sistemática y predecible." },
      { type: "heading", level: 2, text: "Sesgo de confirmación", id: "confirmacion" },
      { type: "paragraph", text: "Buscamos y recordamos la información que confirma lo que ya creemos, e ignoramos la que nos contradice. Es la razón por la que las discusiones rara vez cambian opiniones y por la que conviene buscar activamente puntos de vista contrarios." },
      { type: "heading", level: 2, text: "Aversión a la pérdida", id: "aversion" },
      { type: "paragraph", text: "Perder cien euros duele más que la alegría de ganarlos. Este desequilibrio nos empuja a decisiones conservadoras y a aferrarnos a lo que ya tenemos, aunque no nos convenga." },
      { type: "table", head: ["Sesgo", "Cómo se manifiesta"], rows: [
        ["Anclaje", "El primer número que oyes condiciona toda tu valoración."],
        ["Efecto halo", "Si alguien te cae bien, asumes que también es competente."],
        ["Sesgo del superviviente", "Solo ves los casos de éxito y sacas conclusiones erróneas."],
      ] },
      { type: "callout", tone: "tip", title: "El antídoto", text: "No puedes apagar los sesgos, pero sí crear hábitos: pedir una segunda opinión, dormir antes de decidir y preguntarte «¿qué me haría cambiar de idea?»." },
    ],
  },
  {
    slug: "poner-limites-sin-culpa",
    title: "Cómo poner límites sin sentirte culpable",
    excerpt: "Decir «no» no te hace egoísta. Aprender a hacerlo con serenidad protege tus relaciones y tu salud mental.",
    image: img("1516585427167-9f4af9627e6c", "Persona reflexionando en un momento de calma"),
    coverSeed: "limites",
    category: "psicologia",
    tags: ["relaciones", "bienestar", "comportamiento"],
    author: "mara-costa",
    publishedAt: daysAgo(21),
    views: 24300,
    comments: 52,
    blocks: [
      { type: "paragraph", text: "A muchas personas les cuesta poner límites por miedo a decepcionar o a parecer egoístas. Pero un límite no es un muro contra los demás: es una forma de cuidar la relación siendo honesto sobre lo que puedes y no puedes dar." },
      { type: "heading", level: 2, text: "La culpa no significa que hagas algo malo", id: "culpa" },
      { type: "paragraph", text: "Sentir culpa al decir «no» suele ser un hábito emocional, no una señal de error. Con la práctica, esa culpa se atenúa y aparece algo más valioso: el respeto por tu propio tiempo y energía." },
      { type: "heading", level: 2, text: "Cómo decir no con respeto", id: "como" },
      { type: "list", ordered: false, items: [
        "Sé claro y breve: las excusas largas invitan a negociar.",
        "Reconoce al otro: «entiendo que lo necesitas, y aun así no puedo».",
        "Ofrece una alternativa solo si de verdad quieres.",
      ] },
      { type: "quote", text: "Cada vez que dices «sí» a algo por compromiso, le dices «no» a algo que sí te importa.", cite: "Mara Costa" },
      { type: "paragraph", text: "Los límites sanos no alejan a las personas que te quieren; filtran las relaciones que solo funcionaban mientras te ignorabas a ti mismo." },
    ],
  },
  {
    slug: "habitos-como-se-forman",
    title: "Cómo se forman los hábitos (y cómo cambiarlos de verdad)",
    excerpt: "Señal, rutina y recompensa: el bucle que gobierna casi todo lo que haces en piloto automático.",
    image: img("1522075469751-3a6694fb2f61", "Libros y cuaderno sobre una mesa de trabajo"),
    coverSeed: "habitos",
    category: "psicologia",
    tags: ["hábitos", "comportamiento", "bienestar"],
    author: "dario-fuentes",
    publishedAt: daysAgo(29),
    views: 18600,
    comments: 28,
    blocks: [
      { type: "paragraph", text: "Casi la mitad de lo que hacemos cada día no son decisiones, sino hábitos: conductas automáticas que el cerebro repite para ahorrar esfuerzo. Entender su mecánica es la forma más realista de cambiarlos." },
      { type: "heading", level: 2, text: "El bucle del hábito", id: "bucle" },
      { type: "paragraph", text: "Todo hábito sigue un patrón: una señal lo dispara, una rutina lo ejecuta y una recompensa lo refuerza. Si quieres cambiar un hábito, no luches contra la rutina: identifica la señal y la recompensa que lo sostienen." },
      { type: "callout", tone: "info", title: "Regla práctica", text: "Para crear un hábito, engánchalo a algo que ya haces: «después de servirme el café, escribo tres líneas». La señal ya existe; solo añades la rutina." },
      { type: "heading", level: 2, text: "Por qué fallan los propósitos", id: "propositos" },
      { type: "paragraph", text: "Los grandes propósitos fracasan porque dependen de la motivación, que es voluble. Los hábitos pequeños y consistentes ganan porque no necesitan fuerza de voluntad: se vuelven automáticos. Apunta a lo diminuto y sostenible." },
    ],
  },
  {
    slug: "soledad-y-conexion-social",
    title: "La soledad no deseada y el poder subestimado de las pequeñas conexiones",
    excerpt: "No hace falta una vida social frenética. La ciencia sugiere que los vínculos débiles importan más de lo que creemos.",
    image: img("1494790108377-be9c29b29330", "Retrato de una persona sonriendo con calidez"),
    coverSeed: "soledad",
    category: "psicologia",
    tags: ["relaciones", "bienestar", "comportamiento"],
    author: "mara-costa",
    publishedAt: daysAgo(38),
    views: 15900,
    comments: 24,
    blocks: [
      { type: "paragraph", text: "La soledad no deseada se ha convertido en un problema de salud pública. Pero combatirla no exige transformarte en alguien extrovertido: gran parte del bienestar social viene de interacciones pequeñas y frecuentes." },
      { type: "heading", level: 2, text: "Los vínculos débiles cuentan", id: "vinculos" },
      { type: "paragraph", text: "El vecino con quien charlas dos minutos, el camarero de siempre, el compañero de gimnasio: estos «vínculos débiles» aportan una sensación de pertenencia que la investigación relaciona con más felicidad cotidiana." },
      { type: "heading", level: 2, text: "Pequeños gestos, gran efecto", id: "gestos" },
      { type: "list", ordered: false, items: [
        "Saluda por su nombre a las personas que ves a diario.",
        "Manda un mensaje breve a alguien en quien pensaste.",
        "Acepta la invitación aunque te dé pereza: casi siempre te alegras.",
      ] },
      { type: "paragraph", text: "Conectar es una habilidad que se atrofia sin uso y se fortalece con la práctica. Empieza por lo pequeño; lo grande llega solo." },
    ],
  },
];

// ── HISTORIA & NEGOCIOS ────────────────────────────────────────────────────
const historia: Article[] = [
  {
    slug: "historia-de-apple-garaje-a-gigante",
    title: "De un garaje a la empresa más valiosa: la historia de Apple",
    excerpt: "Fracasos, un despido legendario y un regreso improbable. La trayectoria de Apple es un manual de negocio y de obstinación.",
    image: img("1517486808906-6ca8b3f04846", "Espacio de trabajo con dispositivos tecnológicos"),
    coverSeed: "apple",
    category: "historia-negocios",
    tags: ["empresas", "tecnología", "historia"],
    author: "noa-ibrahim",
    publishedAt: daysAgo(4),
    featured: true,
    trending: true,
    views: 44100,
    comments: 81,
    blocks: [
      { type: "paragraph", text: "En 1976, dos jóvenes montaron ordenadores en un garaje de California. Cuatro décadas después, esa empresa valdría billones. Pero el camino de Apple estuvo lejos de ser una línea recta: fue una montaña rusa de aciertos brillantes y errores casi fatales." },
      { type: "heading", level: 2, text: "El garaje y la primera gran apuesta", id: "garaje" },
      { type: "paragraph", text: "El primer producto era una placa para aficionados. La verdadera revolución llegó con un ordenador personal pensado para gente normal, no para ingenieros. Esa idea —tecnología accesible y bien diseñada— se convertiría en el ADN de la compañía." },
      { type: "heading", level: 2, text: "El despido que lo cambió todo", id: "despido" },
      { type: "paragraph", text: "A mediados de los ochenta, la empresa apartó a uno de sus fundadores. Lejos de hundirlo, aquel exilio le permitió madurar, fundar otras compañías y volver años después con la visión afinada. Uno de los regresos más célebres de la historia empresarial." },
      { type: "callout", tone: "info", title: "La lección", text: "Apple no ganó por tener siempre la mejor tecnología, sino por integrar hardware, software y diseño en una experiencia coherente. Vendía sensaciones, no fichas técnicas." },
      { type: "heading", level: 2, text: "El regreso y la reinvención", id: "regreso" },
      { type: "paragraph", text: "La empresa estaba al borde de la quiebra cuando su fundador regresó. Recortó la línea de productos a unos pocos, apostó por el diseño radical y, con una serie de lanzamientos icónicos, redefinió industrias enteras: la música, la telefonía y la informática personal." },
      { type: "quote", text: "La gente no sabe lo que quiere hasta que se lo enseñas. Ese fue, durante décadas, el motor de Apple.", cite: "Redacción HyperNews" },
      { type: "faq", items: [
        { q: "¿Qué hizo diferente a Apple frente a sus rivales?", a: "La obsesión por la experiencia completa: controlar hardware y software para que todo funcionara junto, con un diseño cuidado hasta el último detalle." },
        { q: "¿Fue siempre una empresa exitosa?", a: "No. Estuvo al borde de la quiebra en los noventa. Su recuperación es uno de los grandes giros de la historia empresarial moderna." },
      ] },
    ],
  },
  {
    slug: "como-nintendo-sobrevivio-un-siglo",
    title: "Nintendo: la empresa que sobrevivió más de un siglo reinventándose",
    excerpt: "Empezó fabricando naipes en 1889. Su secreto no fue la tecnología, sino una asombrosa capacidad de cambiar de piel.",
    image: img("1553729459-efe14ef6055d", "Piezas de juego sobre una superficie"),
    coverSeed: "nintendo",
    category: "historia-negocios",
    tags: ["empresas", "historia", "videojuegos"],
    author: "hugo-serrano",
    publishedAt: daysAgo(11),
    trending: true,
    views: 27300,
    comments: 39,
    blocks: [
      { type: "paragraph", text: "Pocas empresas pueden presumir de más de un siglo de vida. Nintendo nació en 1889 fabricando naipes tradicionales japoneses. Antes de conquistar el mundo con los videojuegos, probó suerte con taxis, hoteles e incluso comida instantánea." },
      { type: "heading", level: 2, text: "Un siglo de reinvenciones", id: "reinvenciones" },
      { type: "paragraph", text: "La historia de Nintendo es la de una empresa que nunca se enamoró de su producto, sino de su capacidad de entretener. Cuando los naipes dejaron de crecer, buscó nuevos caminos hasta dar con los juguetes electrónicos y, después, con las consolas." },
      { type: "heading", level: 2, text: "Jugar donde nadie mira", id: "estrategia" },
      { type: "paragraph", text: "Su gran acierto estratégico fue negarse a competir en potencia bruta contra rivales más grandes. En lugar de eso, apostó por la creatividad y por llegar a públicos que la industria ignoraba: familias, mayores, gente que nunca se había considerado jugadora." },
      { type: "callout", tone: "tip", title: "La lección de negocio", text: "No siempre gana quien tiene la mejor tecnología, sino quien entiende mejor a un público al que nadie más presta atención." },
      { type: "paragraph", text: "En un sector donde las empresas nacen y mueren en una década, la longevidad de Nintendo demuestra el valor de una identidad flexible: fiel a un propósito, libre en los medios." },
    ],
  },
  {
    slug: "burbuja-puntocom-lecciones",
    title: "La burbuja puntocom: qué pasó y qué podemos aprender hoy",
    excerpt: "A finales de los noventa, internet prometía riqueza infinita. El estallido arruinó a muchos y dejó lecciones que siguen vigentes.",
    image: img("1460925895917-afdab827c52f", "Gráficos financieros en una pantalla"),
    coverSeed: "puntocom",
    category: "historia-negocios",
    tags: ["negocios", "tecnología", "historia"],
    author: "noa-ibrahim",
    publishedAt: daysAgo(19),
    views: 21600,
    comments: 34,
    blocks: [
      { type: "paragraph", text: "Entre 1995 y 2000, cualquier empresa que añadiera «.com» a su nombre parecía multiplicar su valor de la noche a la mañana. Los inversores compraban promesas sin beneficios. Cuando la realidad llamó a la puerta, el desplome fue brutal." },
      { type: "heading", level: 2, text: "El entusiasmo sin cimientos", id: "entusiasmo" },
      { type: "paragraph", text: "Muchas startups gastaban millones en publicidad sin un modelo de negocio real. La lógica era «crece ahora, gana dinero después». Funcionó mientras hubo dinero fácil; cuando se agotó, cientos de empresas desaparecieron en meses." },
      { type: "heading", level: 2, text: "Lo que sobrevivió y por qué", id: "supervivientes" },
      { type: "paragraph", text: "No todo fue humo. Las empresas que sobrevivieron compartían algo aburrido pero decisivo: ingresos reales, disciplina de costes y una propuesta que la gente necesitaba de verdad. Sobre esas bases se construyó la internet que hoy usamos." },
      { type: "table", head: ["Señal de burbuja", "Entonces y ahora"], rows: [
        ["Valoraciones sin beneficios", "Precios que ignoran la rentabilidad real."],
        ["«Esta vez es diferente»", "La frase más cara de la historia financiera."],
        ["Miedo a quedarse fuera", "El FOMO empuja a comprar en máximos."],
      ] },
      { type: "callout", tone: "warn", title: "El eco actual", text: "Cada nueva tecnología revive el mismo patrón. La innovación puede ser real y la burbuja también: ambas cosas pueden ser ciertas a la vez." },
    ],
  },
  {
    slug: "historia-del-codigo-de-barras",
    title: "La pequeña gran invención que cambió el comercio: el código de barras",
    excerpt: "Nació de un dibujo en la arena de una playa y hoy mueve la economía global. La historia de un invento invisible.",
    image: img("1524178232363-1fb2b075b655", "Interior de una biblioteca histórica"),
    coverSeed: "barcode",
    category: "historia-negocios",
    tags: ["tecnología", "historia", "innovación"],
    author: "dario-fuentes",
    publishedAt: daysAgo(27),
    views: 14200,
    comments: 17,
    blocks: [
      { type: "paragraph", text: "Lo escaneamos decenas de veces al día sin fijarnos. El código de barras es uno de esos inventos invisibles que sostienen la economía moderna, y su historia es más sorprendente de lo que parece." },
      { type: "heading", level: 2, text: "Una idea dibujada en la arena", id: "arena" },
      { type: "paragraph", text: "Según la leyenda, su inventor concibió el patrón de líneas mientras trazaba surcos en la arena de una playa. La idea era simple: codificar información en un dibujo que una máquina pudiera leer al instante." },
      { type: "heading", level: 2, text: "Décadas hasta triunfar", id: "decadas" },
      { type: "paragraph", text: "Como tantas grandes ideas, tardó años en imponerse. Necesitó lectores baratos, un estándar común entre fabricantes y la confianza del comercio. Cuando todo encajó, transformó la logística, el inventario y la caja del supermercado." },
      { type: "callout", tone: "info", title: "La lección", text: "Una invención no cambia el mundo cuando se concibe, sino cuando el ecosistema a su alrededor está listo para adoptarla." },
      { type: "paragraph", text: "La próxima vez que oigas ese «bip» en la caja, recuerda que estás escuchando una de las infraestructuras más silenciosas y decisivas del comercio global." },
    ],
  },
  {
    slug: "ford-linea-de-montaje",
    title: "La línea de montaje: cómo Ford reinventó el trabajo (para bien y para mal)",
    excerpt: "Multiplicó la producción y creó la clase media, pero también deshumanizó la fábrica. Un legado lleno de matices.",
    image: img("1486406146926-c627a92ad1ab", "Edificio industrial de arquitectura moderna"),
    coverSeed: "ford",
    category: "historia-negocios",
    tags: ["empresas", "historia", "negocios"],
    author: "noa-ibrahim",
    publishedAt: daysAgo(35),
    views: 16800,
    comments: 21,
    blocks: [
      { type: "paragraph", text: "A principios del siglo XX, fabricar un automóvil era lento y carísimo. Ford introdujo una idea que cambiaría la industria para siempre: llevar el trabajo al obrero mediante una cinta en movimiento, en lugar de mover al obrero por la fábrica." },
      { type: "heading", level: 2, text: "Más coches, más baratos", id: "produccion" },
      { type: "paragraph", text: "La línea de montaje redujo drásticamente el tiempo de fabricación y, con ello, el precio. Por primera vez, el coche dejó de ser un lujo para convertirse en un producto al alcance de la clase trabajadora. Fue una revolución económica y social." },
      { type: "heading", level: 2, text: "El precio humano", id: "precio" },
      { type: "paragraph", text: "Pero la eficiencia tuvo un coste. El trabajo repetitivo y monótono generó desgaste y rotación. Ford respondió duplicando el salario, una decisión audaz que retuvo a los trabajadores y, de paso, creó consumidores capaces de comprar sus propios coches." },
      { type: "quote", text: "Si hubiera preguntado a la gente qué quería, habrían dicho caballos más rápidos.", cite: "Atribuida a Henry Ford" },
      { type: "paragraph", text: "El legado de la línea de montaje es ambivalente: disparó la prosperidad y, a la vez, planteó preguntas sobre el sentido del trabajo que seguimos haciéndonos hoy en la era de la automatización." },
    ],
  },
  {
    slug: "por-que-fracasan-las-empresas-familiares",
    title: "Por qué tantas empresas familiares no llegan a la tercera generación",
    excerpt: "Un patrón se repite en todo el mundo: la primera funda, la segunda mantiene y la tercera pierde. ¿Se puede romper?",
    image: img("1450101499163-c8848c66ca85", "Documentos y escritura antigua sobre una mesa"),
    coverSeed: "familiar",
    category: "historia-negocios",
    tags: ["negocios", "empresas", "estrategia"],
    author: "noa-ibrahim",
    publishedAt: daysAgo(48),
    views: 13100,
    comments: 15,
    blocks: [
      { type: "paragraph", text: "Existe un dicho que se repite en muchas culturas: «el abuelo la funda, el hijo la mantiene y el nieto la arruina». Detrás de ese refrán hay un fenómeno real y estudiado: la mayoría de las empresas familiares no sobreviven a la tercera generación." },
      { type: "heading", level: 2, text: "Del hambre a la comodidad", id: "hambre" },
      { type: "paragraph", text: "El fundador construye desde la necesidad y el riesgo. La siguiente generación, formada y prudente, consolida. La tercera, criada en la abundancia, a menudo carece del hambre que originó el negocio y de la conexión con su propósito." },
      { type: "heading", level: 2, text: "Cómo romper la maldición", id: "romper" },
      { type: "list", ordered: false, items: [
        "Separar la propiedad de la gestión: no todo heredero debe dirigir.",
        "Profesionalizar con talento externo sin perder los valores.",
        "Educar a la siguiente generación en el porqué, no solo en el qué.",
      ] },
      { type: "callout", tone: "tip", title: "La clave", text: "Las familias empresarias que perduran tratan la empresa como un legado que administrar, no como una herencia que gastar." },
      { type: "paragraph", text: "Romper el patrón es difícil, pero no imposible. Exige gobernanza, humildad y la voluntad de dejar entrar a quien mejore lo que la familia empezó." },
    ],
  },
];

/** The full corpus — real articles only, across the three verticals. */
export const allArticles: Article[] = [...ia, ...psicologia, ...historia];
